version: "3.9"

services:
  backend:
    image: deployecho-backend:${TAG}
    container_name: deployecho-backend
    environment:
      ENV: dev
      VERSION: docker-compose
      SERVICE: deployecho-backend
    expose:
      - "8080"

  frontend:
    image: deployecho-frontend:${TAG}
    container_name: deployecho-frontend
    expose:
      - "80"

  proxy:
    image: nginx:1.27-alpine
    container_name: deployecho-proxy
    ports:
      - "8088:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

