apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployecho-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: deployecho-backend
  template:
    metadata:
      labels:
        app: deployecho-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "{{ .Values.global.environment }}"
