global:
  environment: staging

backend:
  replicaCount: 1
  image:
    repository: 826828992763.dkr.ecr.us-east-1.amazonaws.com/deployecho-backend
    tag: e4017e1-1
    pullPolicy: IfNotPresent

frontend:
  replicaCount: 1
  image:
    repository: 826828992763.dkr.ecr.us-east-1.amazonaws.com/deployecho-frontend
    tag: e4017e1-1
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: alb
